name: Test and Deploy and Print Contextn Project 
on: [push, workflow_dispatch]
jobs:
  # This job is used to print the context of the workflow
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        # This is a way to print the context of the workflow
        run: echo "Context: ${{ toJson(github) }}"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
      #This is a existing action that is provided by github to checkout the code from the repository
        uses: actions/checkout@v6
      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Install dependencies
      # prefer npm ci over npm install because it is faster and more reliable to install dependencies as 
        run: npm ci 
      - name: Run tests
        run: npm test
  deploy:
    # This is a way to depend on the test job and only run the deploy job if the test job succeeds
    # By default, jobs run in parallel if they don't depend on each other
    needs: test
    # Everyjob runs gets it own runner its own virtual machine and it is isolated from the other jobs
    runs-on: ubuntu-latest
    steps:
      - name: Get code
   
        uses: actions/checkout@v6
      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Install dependencies
      # prefer npm ci over npm install because it is faster and more reliable to install dependencies as 
        run: npm ci 
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
  

        